=== henningBunk/bibliography-exporter/story-template-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "author",
    "title-german",
    "title-original",
    "year",
    "published",
    "source",
    "chapters"
  ],
  "properties": {
    "author": {
      "$id": "#/properties/author",
      "type": "string",
      "title": "The Author Schema",
      "default": "",
      "examples": [
        "H.P. Lovecraft"
      ],
      "pattern": "^(.*)$"
    },
    "title-german": {
      "$id": "#/properties/title-german",
      "type": "string",
      "title": "The Title-german Schema",
      "default": "",
      "examples": [
        "Der Fl√ºsterer im Dunkeln"
      ],
      "pattern": "^(.*)$"
    },
    "title-original": {
      "$id": "#/properties/title-original",
      "type": "string",
      "title": "The Title-original Schema",
      "default": "",
      "examples": [
        "A Whisperer in Darkness"
      ],
      "pattern": "^(.*)$"
    },
    "year": {
      "$id": "#/properties/year",
      "type": "integer",
      "title": "The Year Schema",
      "default": 0,
      "examples": [
        1930
      ]
    },
    "published": {
      "$id": "#/properties/published",
      "type": "string",
      "title": "The Published Schema",
      "default": "",
      "examples": [
        "1932, Pulp Horror Magazin"
      ],
      "pattern": "^(.*)$"
    },
    "source": {
      "$id": "#/properties/source",
      "type": "string",
      "title": "The Source Schema",
      "default": "",
      "examples": [
        "Lovecrafts besten Geschichten / Festa / 1982"
      ],
      "pattern": "^(.*)$"
    },
    "translation": {
      "$id": "#/properties/translation",
      "type": "string",
      "title": "The Translation Schema",
      "default": "",
      "examples": [
        "Erika Fuchs"
      ],
      "pattern": "^(.*)$"
    },
    "category": {
      "$id": "#/properties/category",
      "type": "string",
      "title": "The Category Schema",
      "default": "",
      "examples": [
        "Cthulhu Mythos"
      ],
      "pattern": "^(.*)$"
    },
    "preface": {
      "$id": "#/properties/preface",
      "type": "object",
      "title": "The Preface Schema",
      "default": null,
      "properties": {
        "author": {
          "$id": "#/properties/preface/properties/author",
          "type": "string",
          "title": "The Author Schema",
          "default": "",
          "examples": [
            "Stephen King"
          ],
          "pattern": "^(.*)$"
        },
        "content": {
          "$id": "#/properties/preface/properties/content",
          "type": "string",
          "title": "The Content Schema",
          "default": "",
          "examples": [
            "Dies ist eine tolle Geschichte weil..."
          ],
          "pattern": "^(.*)$"
        }
      },
      "required": [
        "content"
      ]
    },
    "chapters": {
      "$id": "#/properties/chapters",
      "type": "array",
      "title": "The Chapters Schema",
      "items": {
        "$id": "#/properties/chapters/items",
        "type": "object",
        "title": "The Items Schema",
        "properties": {
          "title": {
            "$id": "#/properties/chapters/items/properties/title",
            "type": "string",
            "title": "The Title Schema",
            "default": "",
            "examples": [
              "Kapitel I"
            ],
            "pattern": "^(.*)$"
          },
          "content": {
            "$id": "#/properties/chapters/items/properties/content",
            "type": "string",
            "title": "The Content Schema",
            "default": "",
            "examples": [
              "It was in the township of Dunwich, in a large and partly inhabited farmhouse set against..."
            ],
            "pattern": "^(.*)$"
          }
        },
        "required": [
          "content"
        ]
      }
    }
  }
}

=== henningBunk/bibliography-exporter/story/no-chapters.json
{
  "author": "H.P. Lovecraft",
  "title-german": "Die Ratten im Gemäuer",
  "title-original": "Rats in the walls",
  "year": 1933,
  "published": "1935, reddit",
  "source": "Lovecrafts besten Geschichten / Festa / 1982",

  "chapters": [
    {
      "content": "It was in the township of Dunwich, in a large and partly inhabited farmhouse set against a hillside four miles from the village and a mile and a half from any other dwelling, that Wilbur Whateley was born at 5 a.m. on Sunday, the second of February, 1913. This date was recalled because it was Candlemas, which people in Dunwich curiously observe under another name; and because the noises in the hills had sounded, and all the dogs of the countryside had barked persistently, throughout the night before. Less worthy of notice was the fact that the mother was one of the decadent Whateleys, a somewhat deformed, unattractive albino woman of thirty-five, living with an aged and half-insane father about whom the most frightful tales of wizardry had been whispered in his youth. Lavinia Whateley had no known husband, but according to the custom of the region made no attempt to disavow the child; concerning the other side of whose ancestry the country folk might—and did—speculate as widely as they chose. On the contrary, she seemed strangely proud of the dark, goatish-looking infant who formed such a contrast to her own sickly and pink-eyed albinism, and was heard to mutter many curious prophecies about its unusual powers and tremendous future.\nLavinia was one who would be apt to mutter such things, for she was a lone creature given to wandering amidst thunderstorms in the hills and trying to read the great odorous books which her father had inherited through two centuries of Whateleys, and which were fast falling to pieces with age and wormholes. She had never been to school, but was filled with disjointed scraps of ancient lore that Old Whateley had taught her. The remote farmhouse had always been feared because of Old Whateley's reputation for black magic, and the unexplained death by violence of Mrs Whateley when Lavinia was twelve years old had not helped to make the place popular. Isolated among strange influences, Lavinia was fond of wild and grandiose day-dreams and singular occupations; nor was her leisure much taken up by household cares in a home from which all standards of order and cleanliness had long since disappeared.\nThere was a hideous screaming which echoed above even the hill noises and the dogs' barking on the night Wilbur was born, but no known doctor or midwife presided at his coming. Neighbours knew nothing of him till a week afterward, when Old Whateley drove his sleigh through the snow into Dunwich Village and discoursed incoherently to the group of loungers at Osborne's general store. There seemed to be a change in the old man—an added element of furtiveness in the clouded brain which subtly transformed him from an object to a subject of fear—though he was not one to be perturbed by any common family event. Amidst it all he showed some trace of the pride later noticed in his daughter, and what he said of the child's paternity was remembered by many of his hearers years afterward.,\n\"I dun't keer what folks think—ef Lavinny's boy looked like his pa, he wouldn't look like nothin' ye expeck. Ye needn't think the only folks is the folks hereabouts. Lavinny's read some, an' has seed some things the most o' ye only tell abaout. I calc'late her man is as good a husban' as ye kin find this side of Aylesbury; an' ef ye knowed as much abaout the hills as I dew, ye wouldn't ast no better church weddin' nor her'n. Let me tell ye suthin—some day yew folks'll hear a child o' Lavinny's a-callin' its father's name on the top o' Sentinel Hill!\"\nThe only person who saw Wilbur during the first month of his life were old Zechariah Whateley, of the undecayed Whateleys, and Earl Sawyer's common-law wife, Mamie Bishop. Mamie's visit was frankly one of curiosity, and her subsequent tales did justice to her observations; but Zechariah came to lead a pair of Alderney cows which Old Whateley had bought of his son Curtis. This marked the beginning of a course of cattle-buying on the part of small Wilbur's family which ended only in 1928, when the Dunwich horror came and went; yet at no time did the ramshackle Whateley barn seem overcrowded with livestock. There came a period when people were curious enough to steal up and count the herd that grazed precariously on the steep hillside above the old farm-house, and they could never find more than ten or twelve anaemic, bloodless-looking specimens. Evidently some blight or distemper, perhaps sprung from the unwholesome pasturage or the diseased fungi and timbers of the filthy barn, caused a heavy mortality amongst the Whateley animals. Odd wounds or sores, having something of the aspect of incisions, seemed to afflict the visible cattle; and once or twice during the earlier months certain callers fancied they could discern similar sores about the throats of the grey, unshaven old man and his slatternly, crinkly-haired albino daughter."
    }
  ]
}
